// Generated by CoffeeScript 1.3.3

angular.module('DemoApp', ['timepickr']).controller('DemoCtrl', function($scope) {
  return $scope.test_time = '05:27 PM';
}).controller('DemoCtrl2', function($scope) {
  return $scope.data = {
    test_time: '12:12 am'
  };
});
